#!/usr/bin/env ruby
# frozen_string_literal: true

# Main module of the script
module LogParser
  require './lib/validator'
  require './lib/core'
  require './lib/printer'

  def self.run
    filename = ARGV[0]
    Validator.run(filename)
    results = Core.run(filename)
    Printer.run(filename, results)
  end
end

LogParser.run
